// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_complete_a_song = "CgkIqOuDgc4PEAIQDA"; // <GPGSID>
        public const string achievement_combo_master_lll = "CgkIqOuDgc4PEAIQBw"; // <GPGSID>
        public const string achievement_new_color = "CgkIqOuDgc4PEAIQCQ"; // <GPGSID>
        public const string achievement_jump_over_your_limit_l = "CgkIqOuDgc4PEAIQAg"; // <GPGSID>
        public const string achievement_rich = "CgkIqOuDgc4PEAIQCA"; // <GPGSID>
        public const string achievement_long_lifetime = "CgkIqOuDgc4PEAIQCw"; // <GPGSID>
        public const string achievement_are_you_a_dj = "CgkIqOuDgc4PEAIQDQ"; // <GPGSID>
        public const string achievement_jump_over_your_limit_lll = "CgkIqOuDgc4PEAIQBA"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIqOuDgc4PEAIQAQ"; // <GPGSID>
        public const string achievement_combo_master_ll = "CgkIqOuDgc4PEAIQBg"; // <GPGSID>
        public const string achievement_jump_over_your_limit_ll = "CgkIqOuDgc4PEAIQAw"; // <GPGSID>
        public const string achievement_combo_master_l = "CgkIqOuDgc4PEAIQBQ"; // <GPGSID>
        public const string achievement_rainbow_color = "CgkIqOuDgc4PEAIQCg"; // <GPGSID>

}

