// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard______3 = "CgkI7se0pOoFEAIQEg"; // <GPGSID>
        public const string leaderboard______1 = "CgkI7se0pOoFEAIQCQ"; // <GPGSID>
        public const string achievement____2 = "CgkI7se0pOoFEAIQCw"; // <GPGSID>
        public const string achievement____2_3 = "CgkI7se0pOoFEAIQDQ"; // <GPGSID>
        public const string leaderboard______1_2 = "CgkI7se0pOoFEAIQCg"; // <GPGSID>
        public const string achievement____1_2 = "CgkI7se0pOoFEAIQBw"; // <GPGSID>
        public const string achievement____1 = "CgkI7se0pOoFEAIQBg"; // <GPGSID>
        public const string leaderboard______2 = "CgkI7se0pOoFEAIQDw"; // <GPGSID>
        public const string achievement____2_2 = "CgkI7se0pOoFEAIQDA"; // <GPGSID>
        public const string achievement____1_3 = "CgkI7se0pOoFEAIQCA"; // <GPGSID>
        public const string achievement__12 = "CgkI7se0pOoFEAIQBA"; // <GPGSID>
        public const string achievement__24 = "CgkI7se0pOoFEAIQBQ"; // <GPGSID>
        public const string leaderboard______2_2 = "CgkI7se0pOoFEAIQEA"; // <GPGSID>
        public const string achievement__6 = "CgkI7se0pOoFEAIQAw"; // <GPGSID>

}

